ARG GO_VERSION=1.25
FROM golang:${GO_VERSION}

ARG HUGO_VERSION=0.154.4
RUN apt-get update && apt-get install -y wget ca-certificates && \
    ARCH=$(dpkg --print-architecture) && \
    wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-${ARCH}.tar.gz && \
    tar -C /usr/local/bin -xzf /tmp/hugo.tar.gz hugo && \
    rm /tmp/hugo.tar.gz

WORKDIR /app

ENTRYPOINT [ "hugo" ]
